### ISSUE TITLE
ConcurrentModificationException in AnnotationUsageCache

### ISSUE THREAD

**Issue by phax** [phax/ph-commons#27]
```
java.util.ConcurrentModificationException: null
at java.util.HashMap.computeIfAbsent(HashMap.java:1135) ~[?:?]
at com.helger.commons.cache.AnnotationUsageCache.hasAnnotation(AnnotationUsageCache.java:95) ~[ph-commons-10.1.5.jar:10.1.5]
at com.helger.commons.hashcode.HashCodeImplementationRegistry._isUseDirectHashCode(HashCodeImplementationRegistry.java:131) ~[ph-commons-10.1.5.jar:10.1.5]
at com.helger.commons.hashcode.HashCodeImplementationRegistry.getBestMatchingHashCodeImplementation(HashCodeImplementationRegistry.java:176) ~[ph-commons-10.1.5.jar:10.1.5]
at com.helger.commons.hashcode.HashCodeImplementationRegistry.getHashCode(HashCodeImplementationRegistry.java:260) ~[ph-commons-10.1.5.jar:10.1.5]
at com.helger.commons.hashcode.HashCodeCalculator.append(HashCodeCalculator.java:175) ~[ph-commons-10.1.5.jar:10.1.5]
at com.helger.commons.hashcode.HashCodeGenerator.append(HashCodeGenerator.java:472) ~[ph-commons-10.1.5.jar:10.1.5]
at com.helger.commons.mime.MimeType.hashCode(MimeType.java:344) ~[ph-commons-10.1.5.jar:10.1.5]
at java.util.HashMap.hash(HashMap.java:340) ~[?:?]
at java.util.HashMap.put(HashMap.java:608) ~[?:?]
at com.helger.http.AcceptMimeTypeList.addMimeType(AcceptMimeTypeList.java:56) ~[ph-http-9.6.2.jar:9.6.2]
at com.helger.http.AcceptMimeTypeHandler.getAcceptMimeTypes(AcceptMimeTypeHandler.java:85) ~[ph-http-9.6.2.jar:9.6.2]
at com.helger.servlet.request.RequestHelper.getAcceptMimeTypes(RequestHelper.java:1017) ~[ph-servlet-9.6.2.jar:9.6.2]
at com.helger.servlet.response.UnifiedResponse.<init>(UnifiedResponse.java:199) ~[ph-servlet-9.6.2.jar:9.6.2]
```

**Comment by phax** [comment]
This is new in Java 11 that `HashMap.computeIfAbsent` throws a `ConcurrentModificationException`
